### ISSUE TITLE
Test suite hangs, then fails

### ISSUE THREAD

**Issue by zeke** [segmentio/myth#137]
```
❯ node -v
v5.7.0

~/forks/myth update-rework-import*
❯ npm -v
3.6.0

~/forks/myth update-rework-import*
❯ npm t

> myth@1.5.0 test /Users/z/forks/myth
> make test
```

The process hangs on `make test`...

**Comment by zeke** [comment]
Oh wait it finally finished, with one error:

```
  1) cases should convert myth.io's css:
     AssertionError: '/**\n * Variables.\n */\n\n/**\n * Body.\n */\n\nbody {\n  font: 100 16px/1.5 "Source Sans", sans-serif;\n  color: white;\n  ba == '/**\n * Variables.\n */\n\n/**\n * Body.\n */\n\nbody {\n  font: 100 16px/1.5 "Source Sans", sans-serif;\n  color: white;\n  ba
      at Context.<anonymous> (/Users/z/forks/myth/test/index.js:204:14)
      at callFn (/Users/z/forks/myth/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/Users/z/forks/myth/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/Users/z/forks/myth/node_modules/mocha/lib/runner.js:373:10)
      at /Users/z/forks/myth/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/z/forks/myth/node_modules/mocha/lib/runner.js:298:14)
      at /Users/z/forks/myth/node_modules/mocha/lib/runner.js:308:7
      at next (/Users/z/forks/myth/node_modules/mocha/lib/runner.js:246:23)
      at Immediate._onImmediate (/Users/z/forks/myth/node_modules/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)
```
