### ISSUE TITLE
Problem with Node 6

### ISSUE THREAD

**Issue by pin3da** [segmentio/myth#142]
Hello, I tried to run the samples using node 6 and I got the following error:

```

       error · TypeError: obj.hasOwnProperty is not a function
             ·   at clone (/home/pin3da/repos/in-silico.github.io/node_modules/clone-component/index.js:30:17)
             ·   at clone (/home/pin3da/repos/in-silico.github.io/node_modules/clone-component/index.js:31:23)
             ·   at clone (/home/pin3da/repos/in-silico.github.io/node_modules/clone-component/index.js:31:23)
             ·   at Object.exports.prefixes (/home/pin3da/repos/in-silico.github.io/node_modules/myth/lib/features.js:124:14)
             ·   at /home/pin3da/repos/in-silico.github.io/node_modules/myth/lib/index.js:52:33
             ·   at Array.forEach (native)
             ·   at /home/pin3da/repos/in-silico.github.io/node_modules/myth/lib/index.js:50:22
             ·   at Rework.use (/home/pin3da/repos/in-silico.github.io/node_modules/rework/index.js:50:3)
             ·   at myth (/home/pin3da/repos/in-silico.github.io/node_modules/myth/lib/index.js:36:6)
             ·   at /home/pin3da/repos/in-silico.github.io/node_modules/myth/bin/myth:101:13
```

**Note:** With node 4 it works well.

I changed the module 'clone-component' by 'utils-copy' and it works (with node 6).

I don't know if this is the real solution, but I'm willing to help with some patch if necessary.

Thank you!

**Comment by swantzter** [comment]
May I suggest opening a pr?

**Comment by sbrl** [comment]
Just run into this myself. It's rather annoying that myth (a program that polyfills for future versions of CSS) can't be run on the latest version of node.

Does anyone have a rough estimate of when it'll be fixed?
